### ISSUE TITLE
Panic on episode fetch for patreon feed

### ISSUE THREAD

**Issue by jimmyharris** [SamTV12345/PodFetch#69] opened 2023-04-19 16:05 UTC
### Describe the bug

Trying to add a patreon private feed I get the following error:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/service/podcast_episode_service.rs:234:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:114:5
   3: podfetch::service::podcast_episode_service::PodcastEpisodeService::get_url_file_suffix
   4: podfetch::service::rust_service::PodcastService::handle_insert_of_podcast::{{closure}}
   5: podfetch::controllers::podcast_controller::insert_outline::{{closure}}
   6: futures_executor::local_pool::block_on
   7: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
   8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: tokio::runtime::blocking::pool::Inner::run
```
Looks like patreon file URLS aren't conforming to your regex capture structure correctly.

### Reproduction

add a private patreon feed it will produce this stack trace.

### System Info

```Shell
Not sure how to get this via my docker setup.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment] 2023-04-19 16:52
Thanks for creating a bug report. Do you have a private patreon feed so I can reproduce the issue? I have never tried adding this via mime type but that could facilitate the process. I'm reading indeed the file type from the url.

**Comment by SamTV12345** [comment] 2023-04-21 14:05
Any updates on this one?

**Comment by SamTV12345** [comment] 2023-05-09 22:10
I'll close it in 1 week as this issue seems to be irrelevant. If you really experience this issue again please open a new one with a better description and a way that I can reproduce this issue.

**Comment by SamTV12345** [comment] 2023-05-14 17:59
Closed. Please create a new one with better reproduction.

**Closed by SamTV12345** 2023-05-14 17:59 UTC
Labels: question

**Comment by jimmyharris** [comment] 2023-05-19 15:24
sorry I'll have to give some example data with a new ticket and better reproducibility. I might have to setup a similar hosting setup because I don't really want to give a private patreon feed out since that is something the authors of the feed are offering for pay.

**Comment by SamTV12345** [comment] 2023-05-20 22:00
No problem. You can also send it to [this](mailto:samuelsemailtestsender@gmail.com) email address if you want to keep the url secret.
