### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by janaxhell** [SamTV12345/PodFetch#136] opened 2023-05-21 09:52 UTC
### Describe the bug

I'm trying to deploy this on OMV6/Docker/Portainer.
I have used the docker-compose from home page and added auth and api [redacted], so that it now looks like this:

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH: true
      - USERNAME: XXXXX
      - PASSWORD: XXXXX
      - PODINDEX_API_KEY: XXXXX
      - PODINDEX_API_SECRET: XXXXX
```

As soon as I deploy I get this error:

```
failed to deploy a stack: time="2023-05-21T09:25:45Z" 
level=warning msg="The \"CgSLq4cMC\" variable is not set. Defaulting to a blank string." time="2023-05-21T09:25:45Z" 
level=warning msg="The \"knd\" variable is not set. Defaulting to a blank string." services.podfetch.environment.2 must be a string
```

### Reproduction

Deploy the above compose

### System Info

```Shell
Open Media Vault 6
Docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment] 2023-05-21 09:55
The issue is your Podindex API key. It contains a $. $ is interpreted by Docker. To prevent that add another $ in front/behind the other dollar sign.

**Comment by janaxhell** [comment] 2023-05-21 10:00
There are in fact 2, but changing them to $$ still leads me to

`failed to deploy a stack: services.podfetch.environment.2 must be a string`

**Comment by Chifilly** [comment] 2023-05-21 11:18
Your YAML syntax is incorrect in the environment variables. It should be as follows:
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXX
      - PASSWORD=XXXXX
      - PODINDEX_API_KEY=XXXXX
      - PODINDEX_API_SECRET=XXXXX
```

Arrays in YAML use `=` for value setting, and objects use `:`, and since you're using an array you need to replace the colons with equals signs

**Comment by janaxhell** [comment] 2023-05-21 11:24
Ok, thanks again, but now with all variables replaces with = I get this new error:

`failed to deploy a stack: podfetch Pulling a7ca0d9ba68f Pulling fs layer fe5ca62666f0 Pulling fs layer b02a7525f878 Pulling fs layer fcb6f6d2c998 Pulling fs layer e8c73c638ae9 Pulling fs layer 1e3d9b7d1452 Pulling fs layer 4aa0ea1413d3 Pulling fs layer 7c881f9ab25e Pulling fs layer 5627a970d25e Pulling fs layer 96266735468f Pulling fs layer 80ec95682aee Pulling fs layer f51c8fa85103 Pulling fs layer dfc02eb7708f Pulling fs layer 52907d314ddc Pulling fs layer 4eec690774a4 Pulling fs layer 55ffd214c0e6 Pulling fs layer 11620ec24fb0 Pulling fs layer 3b8c74c5dade Pulling fs layer 4f4fb700ef54 Pulling fs layer 3a3a0eea33cc Pulling fs layer fcb6f6d2c998 Waiting f51c8fa85103 Waiting dfc02eb7708f Waiting 52907d314ddc Waiting 11620ec24fb0 Waiting 4eec690774a4 Waiting 55ffd214c0e6 Waiting 4f4fb700ef54 Waiting 3a3a0eea33cc Waiting 4aa0ea1413d3 Waiting e8c73c638ae9 Waiting 5627a970d25e Waiting 7c881f9ab25e Waiting 96266735468f Waiting 80ec95682aee Waiting a7ca0d9ba68f Downloading [&gt; ] 1.369kB/103.7kB fe5ca62666f0 Downloading [===&gt; ] 1.369kB/21.2kB fe5ca62666f0 Download complete a7ca0d9ba68f
`

**Comment by Chifilly** [comment] 2023-05-21 11:28
I don't see any errors in that apart from `failed to deploy a stack`. Is there nothing else? That just seems like Docker pulling the layers for the image

**Comment by janaxhell** [comment] 2023-05-21 11:31
All the errors appear in a quickly disappearing on-screen frame in Portainer (that I copy with mouse), since the image is not deployed, I don't know where to look for an error log.

**Comment by SamTV12345** [comment] 2023-05-21 11:43
Maybe try again with docker-compose. I can't also see why it is failing. The container even didn't start.

**Comment by Chifilly** [comment] 2023-05-21 11:46
Hmm, I'm not sure. I only use Portainer as a glorified container status and log viewer myself and do everything via the command line, so hopefully someone else has some insight. Maybe post your new compose file to double check everything, but I don't notice any issues in the original other than the colon stuff

In response to your edit, I believe there is a limit to 31 default networks since it seems the default networks are hard-coded. Maybe it's worth creating your own network(s) and assigning containers to them, since if you create your own it can assign a lot more IP addresses to them

As an example, here's the network I have all my media server containers assigned to:
```yaml
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
```
and that will allow me to have 256 containers on that single network, and they can all communicate with each other

**Comment by janaxhell** [comment] 2023-05-21 12:08
How did you choose 172.16.0.0? I'm rather new to selfhosting.
Also, when I create that, how do I assign my other containers? I just add those lines to my composes?

My Podfetch compose is exactly as above, except for ": " replaced with "="

**Comment by Chifilly** [comment] 2023-05-21 12:18
It was just in an example I found forever ago and had no issues with it, so I've used it since. I'm pretty sure it can be anything that isn't already a used subnet. And in your compose file you add a `networks` key and the network name in an array or as an object. for example;
```yaml
services:
  podfetch:
    ...
    networks:
      - my_new_network
    ...
```
or
```yaml
services:
  podfetch:
    ...
    networks:
      my_new_network:
    ...
```
_I prefer the second option, so if I need to add specifics to the network configuration I can, which I had to do for some of my containers, but that's more advanced stuff you probably won't need to do_

They will then be assigned to all the networks under the `networks` key and can talk to each other with their container names. For example, some other container that's also on the `my_new_network` network could then use `http://podfetch:8000` to communicate with it, since as far as the containers are concerned, they're on the same LAN

**Comment by janaxhell** [comment] 2023-05-21 12:26
Since I'm using Portainer to create it, for gateway and IP range, should I use my router IP? 
Like 
Subnet - 172.16.0.0/24
IPV4 Gateway - 192.168.1.1
IPV4 IP Range - 192.168.1.128/24
?

**Comment by Chifilly** [comment] 2023-05-21 12:31
They aren't required. It's just if you want to be more specific with your network configuration for the containers. Docker should automatically assign those values

**Comment by janaxhell** [comment] 2023-05-21 12:36
Eh, I'm almost there, but not quite: 
`failed to deploy a stack: services.networks must be a mapping`
My compose now looks like this and "omv1" is my network and shows as online

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
  networks:
    omv1
```

**Comment by Chifilly** [comment] 2023-05-21 12:38
You need another indentation level on networks and the colon or hyphen was missing
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
    networks:
      omv1: # this line can either be "- omv1" or "omv1:"
````

**Comment by janaxhell** [comment] 2023-05-21 12:42
Argh! Changed indentation and added semicolon, now: 
`failed to deploy a stack: service "podfetch" refers to undefined network omv1: invalid compose project `
but omv1 is there in the list of other networks. 
Maybe I should at least remove one?

**Comment by Chifilly** [comment] 2023-05-21 12:47
I think I know the issue. The network was created outside the stack, but podfetch is inside the stack, and by default Docker prefixes anything inside the stack with the stack name. For example the network it will try and connect podfetch to if the stack was called `mystack` would be `mystack_omv1` which doesn't exist since you made it manually. Try adding the network within the stack with the above example snippet I posted, eg:

```yaml
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
    networks:
      omv1: # this line can either be "- omv1" or "omv1:"

networks:
  omv1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
```

**Comment by janaxhell** [comment] 2023-05-21 12:50
:( 
`failed to deploy a stack: services.podfetch.networks.omv1 Additional property ipam is not allowed`

**Comment by janaxhell** [comment] 2023-05-21 13:04
Yes! I can now deploy it, BUT still no-go:

```
This site can’t be reachedThe webpage at http://192.168.1.94:6666/ might be temporarily down or it may have moved permanently to a new web address.
ERR_UNSAFE_PORT
```

**Comment by Chifilly** [comment] 2023-05-21 13:05
What do the logs show for podfetch? Seems like it might not be able to start properly

**Comment by janaxhell** [comment] 2023-05-21 13:06
This is all I can see
```
Debug file located at /target/x86_64-unknown-linux-gnu/release/build/podfetch-63cd01e1b33fa505/out/built.rs
  ____           _ _____    _       _
 |  _ \ ___   __| |  ___|__| |_ ___| |__
 | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|
        
2023-05-21T13:01:41 [INFO] - No settings found, inserting default settings
2023-05-21T13:01:41 [INFO] - Starting with the following environment variables:
Public server url: http://192.168.1.94:6666/
Polling interval for new episodes: 60 minutes
GPodder integration enabled: false
Database url is set to: sqlite://./db/podcast.db
Podindex API key&secret configured: true
2023-05-21T13:01:41 [INFO] - starting 2 workers
2023-05-21T13:01:41 [INFO] - Actix runtime found; starting in Actix runtime

```

**Comment by SamTV12345** [comment] 2023-05-21 13:11
See [here](https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome) for an explanation. 6666 was an apple service standard port. So please pick another one or choose Firefox.

**Comment by janaxhell** [comment] 2023-05-21 13:15
Ah! How unlucky! Yes, now I have changed port and at last it works!
Thank you so much for the immense patience!

**Comment by SamTV12345** [comment] 2023-05-21 13:18
Yes just export the OPML from Podgrab and add it via the Plus Icon in the podcasts page of PodFetch.

**Comment by janaxhell** [comment] 2023-05-21 13:19
Yes, found, it's adding now! :)

**Comment by SamTV12345** [comment] 2023-05-21 13:20
Nice. Hope it will work now.

**Comment by janaxhell** [comment] 2023-05-21 13:24
Ok, I just add a little clarification for anyone who could read this in the future: it does not recycle Podgrab podcasts. I have set the same folder I use for it and Podfetch is creating all the same podcast-folders with trailing "-1" and a different file structure. 
Not a problem, but better know to avoid duplication of content. :)

**Comment by SamTV12345** [comment] 2023-05-21 13:38
Yes. That is the first initialization. If there is already a folder with the name it adds a digit as long as it finds an existing folder. That other issue is fixed. Try to do a docker compose pull or the equivalent in Portainer.

**Comment by SamTV12345** [comment] 2023-05-21 13:47
Oh and refresh the podcast after that.

**Comment by janaxhell** [comment] 2023-05-21 14:28
Sorry, I had to leave for a while. 
Yes, it now works. 
Only thing I noticed with OPML is that a couple of podcasts that are concluded were not imported, while others concluded as well were imported. I guess it has to do with various platforms policies.

**Comment by SamTV12345** [comment] 2023-05-21 14:55
Weird. It should normally download all listed podcasts. Did you get any logs?

**Comment by janaxhell** [comment] 2023-05-21 15:06
One podcast is SARANADE, it shows in the log, but not in the UI, the other is The Numberphile Podcast and it doesn't show anywhere. 

```
2023-05-21T14:15:16 [INFO] - Settings already present
Public server url: http://192.168.1.94:6656/
Polling interval for new episodes: 60 minutes
GPodder integration enabled: false
2023-05-21T14:15:16 [INFO] - Starting with the following environment variables:
Database url is set to: sqlite://./db/podcast.db
Podindex API key&secret configured: true
2023-05-21T14:15:16 [INFO] - starting 2 workers
2023-05-21T14:15:16 [INFO] - Actix runtime found; starting in Actix runtime
2023-05-21T14:21:03 [INFO] - Refreshing podcast: Letture Filosofiche - UniBo
2023-05-21T14:21:04 [INFO] - Refreshing podcast: DeepMind: The Podcast
2023-05-21T14:21:04 [INFO] - Refreshing podcast: Zoopodcast
2023-05-21T14:21:04 [INFO] - Refreshing podcast: La fine del mondo
2023-05-21T14:21:04 [INFO] - Refreshing podcast: Joypad
2023-05-21T14:21:04 [INFO] - Refreshing podcast: Alma Lectio - UniBo
2023-05-21T14:21:04 [INFO] - Refreshing podcast: The Art of Asking Everything
2023-05-21T14:21:05 [INFO] - Refreshing podcast: Interdependence
2023-05-21T14:21:05 [INFO] - Refreshing podcast: The Real Genius
2023-05-21T14:21:05 [INFO] - Refreshing podcast: Il podcast di Alessandro Barbero: Lezioni e Conferenze di Storia
2023-05-21T14:21:05 [INFO] - Refreshing podcast: Research Corner - Road to 2030 - UniBo
2023-05-21T14:21:05 [INFO] - Refreshing podcast: Dentro alla filosofia
2023-05-21T14:21:06 [INFO] - Refreshing podcast: 99% Invisible
2023-05-21T14:21:06 [INFO] - Refreshing podcast: Zeitgeist Banana
2023-05-21T14:21:06 [INFO] - Refreshing podcast: Dentro alla storia
2023-05-21T14:21:06 [INFO] - Refreshing podcast: OTTN Projects Podcast
2023-05-21T14:21:07 [INFO] - Refreshing podcast: The Three Questions with Andy Richter
2023-05-21T14:21:07 [INFO] - Refreshing podcast: Overheard at National Geographic
2023-05-21T14:21:08 [INFO] - Refreshing podcast: Periodic Talks
2023-05-21T14:21:08 [INFO] - Refreshing podcast: You Are Not So Smart
2023-05-21T14:21:08 [INFO] - Refreshing podcast: Lingthusiasm - A podcast that's enthusiastic about linguistics
2023-05-21T14:21:09 [INFO] - Refreshing podcast: The Curious Cases of Rutherford & Fry
2023-05-21T14:21:09 [INFO] - Refreshing podcast: HonesTEA with Z
2023-05-21T14:21:09 [INFO] - Refreshing podcast: All in the Mind
2023-05-21T14:21:10 [INFO] - Refreshing podcast: SARANADE
2023-05-21T14:21:10 [INFO] - Refreshing podcast: Planet Progress
2023-05-21T14:21:11 [INFO] - Refreshing podcast: The GeekBits Podcast
2023-05-21T14:21:12 [INFO] - Refreshing podcast: Cosa c'entra?
2023-05-21T14:21:12 [INFO] - Refreshing podcast: Whatever Next?
2023-05-21T14:31:07 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=rai
2023-05-21T14:31:14 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=rai%20radio
2023-05-21T14:31:43 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=morning
2023-05-21T14:32:04 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=il%20post
Result: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Som
```
I have tried to add SARANADE from Podindex and this is what happened: 

```
2023-05-21T15:03:03 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=saranade
Result: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.podcastindex.org")), port: None, path: "/api/1.0/podcasts/byfeedid", query: Some("id=1319467"), fragment: None }, status: 200, headers: {"date": "Sun, 21 May 2023 15:03:05 GMT", "content-type": "application/json", "transfer-encoding": "chunked", "connection": "keep-alive", "cache-control": "no-cache, must-revalidate", "x-php-responsecode": "201", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-Auth-Date,X-Auth-Key", "access-control-expose-headers": "Content-Length,Content-Range", "cf-cache-status": "DYNAMIC", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=1LOKx19dB27oGpnADR%2BPVyUHRG%2FE%2FW8Aw4Vs89t10NaBaQcfhBJ1TJP%2BUaL2wiiLwSMkTJ5OO0mnU6ww0ZBl2K5ICPgJRlS3gh1U56POu73kd7jY%2FgL5i%2FwIoGcqkdXPXiKa0JsH\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "server": "cloudflare", "cf-ray": "7cadb441ae66baf3-MXP"} }
2023-05-21T15:03:05 [ERROR] - Error: The following error occurred: Podcast already exists
```
The Numberphile Podcast is confusing, it appears twice in Podindex. I've been able to add one and this is what log said: 

```
2023-05-21T15:04:26 [INFO] - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=the%20numberphile
Result: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.podcastindex.org")), port: None, path: "/api/1.0/podcasts/byfeedid", query: Some("id=520179"), fragment: None }, status: 200, headers: {"date": "Sun, 21 May 2023 15:05:09 GMT", "content-type": "application/json", "transfer-encoding": "chunked", "connection": "keep-alive", "cache-control": "no-cache, must-revalidate", "x-php-responsecode": "201", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-Auth-Date,X-Auth-Key", "access-control-expose-headers": "Content-Length,Content-Range", "cf-cache-status": "DYNAMIC", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=H1FeQNH0DHBfxxqe08JslhbNZSlHxTfGQDw8mks%2FMVS9EFJSGui3Feoz5uXmZuK%2Fg260jUmFIFk3%2Fk%2Ba%2BafHXyvip4EXqV5H9RLyX6E0sBfNwm2YXVz5U9NjVtcVEbX1ULc6twL1\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "server": "cloudflare", "cf-ray": "7cadb7470c3f375f-MXP"} }
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidStartTag', src/service/podcast_episode_service.rs:136:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(485), ...)', src/service/rust_service.rs:179:18
```

**Comment by SamTV12345** [comment] 2023-05-21 15:18
Seems like SARANDE already is added to PodFetch. Concerning the other problem that comes from the library that parses the rss feed. The [rss](https://www.numberphile.com/podcast?format=rss) feed starts with xml instead of rss which is the specification. I'll try to strip the xml before and after the rss tag. Hopefully that will work.

**Comment by janaxhell** [comment] 2023-05-21 15:23
> Seems like SARANDE already is added to PodFetch.

Yes, it says so, but it's nowhere to be seen in the UI. I see all the other podcasts, but not that one.

**Comment by SamTV12345** [comment] 2023-05-21 15:27
![image](https://github.com/SamTV12345/PodFetch/assets/40429738/0e899997-43d5-4ea5-9c52-9f4a6eb8a055)

I can't find the podcast via Podindex.

**Comment by janaxhell** [comment] 2023-05-21 15:31
You wrote SARANDE, it's SARAN-A-DE with A

![image](https://github.com/SamTV12345/PodFetch/assets/55061479/da962e14-ed24-4d05-b18f-128ee4945920)

**Comment by janaxhell** [comment] 2023-05-21 15:57
I have restarted from scratch using a new empty folder for podcasts. This time after adding from Podgrab OPML a coul see SARANADE podcast, but when I clicked it, it showed no episode and as soon as I got back to channel, it was disappeared. No trace of The Numberphile, which I suppose you're still working on.

**Comment by SamTV12345** [comment] 2023-05-21 16:09
Concerning SARANADE this is expected behaviour:


```xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="https://feeds.buzzsprout.com/styles.xsl" type="text/xsl"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:podcast="https://podcastindex.org/namespace/1.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <atom:link href="https://feeds.buzzsprout.com/1455049.rss" rel="self" type="application/rss+xml" />
        <atom:link href="https://pubsubhubbub.appspot.com/" rel="hub" xmlns="http://www.w3.org/2005/Atom" />
        <title>SARANADE</title>
        <lastBuildDate>Sun, 21 May 2023 05:08:31 -0400</lastBuildDate>
        <link>https://saranade.buzzsprout.com</link>
        <language>en-us</language>
        <copyright>© 2023 SARANADE</copyright>
        <podcast:locked>yes</podcast:locked>
        <podcast:guid>a2707ed9-d952-5009-a7ae-46332c2c35dc</podcast:guid>
        <itunes:author>Sara Niemietz</itunes:author>
        <itunes:type>episodic</itunes:type>
        <itunes:explicit>false</itunes:explicit>
        <description>
            <![CDATA[Sara Niemietz shares tour stories, songwriting, puns, and talks with friends! ]]>
        </description>
        <itunes:owner>
            <itunes:name>Sara Niemietz</itunes:name>
        </itunes:owner>
        <image>
            <url>https://storage.buzzsprout.com/variants/7rrsztbonxftjait7did1rvz5xl8/60854458c4d1acdf4e1c2f79c4137142d85d78e379bdafbd69bd34c85f5819ad.jpg</url>
            <title>SARANADE</title>
            <link></link>
        </image>
        <itunes:image href="https://storage.buzzsprout.com/variants/7rrsztbonxftjait7did1rvz5xl8/60854458c4d1acdf4e1c2f79c4137142d85d78e379bdafbd69bd34c85f5819ad.jpg" />
        <itunes:category text="Music" />
        <itunes:category text="Music">
            <itunes:category text="Music Interviews" /></itunes:category>
    </channel>
</rss>
```
As you can see the RSS feed is completely empty. It seems like that Sara Niemitz deleted every reference to her podcast episodes.

**Comment by janaxhell** [comment] 2023-05-21 16:11
Ok, so this explains the ghost entry at first launch.

**Comment by SamTV12345** [comment] 2023-05-21 16:11
That is why:  https://blubrry.com/manual/syndicating-your-podcast-rss-feeds/lock-your-podcast-feed-stop-show-importing-migration/#:~:text=Podcast%20feeds%20can%20be%20locked,platforms%20that%20respect%20the%20tag She doesn't want anyone to listen to her podcasts on other platforms that is why the RSS feed is hidden and shows no entries.

**Comment by janaxhell** [comment] 2023-05-21 16:15
Ah, weird. I added that in first place to MusicBee that AFAIK relies on iTunes. But there is no trace of it on iTunes now. Guess she just closed it for good.

**Closed** 2023-05-21 17:06 UTC
